### ISSUE TITLE
Improper accreditation of the Quotes cog

### ISSUE THREAD

**Issue by Kreusada** [scautura/jimmy-quotes2#14]
Hi there, I search "Kreusada" on Github every few months to find incorrectly copied cogs from my repo. I see you have copied the Quotes cog from my repo.

Please remember that the proper way to modify cogs is to fork their repository, make your changes, and then download from said fork. Alternatively, you can create a pull request with those changes if they are relevant for other users. However, please check if this obeys their license.

My repo uses the MIT License, which is against liability or warranty of the code the repository encapsulates.

These are the changes I would like you to make:

- [ ] Prepend "Kreusada" to the `Quotes.__author__` attribute found inside `quotes/quotes.py`.
- [ ] Prepend "Kreusada" to the `author` key's value found inside `quotes/info.json`.

Whilst the above is a fairly copy-pasted message from other incidents, I do appreciate that you credited my name in the `install_msg` key's value found in `quotes/info.json`. However, this is not where I would like to be credited.

**Comment by scautura** [comment]
I have removed the code from the repository entirely (due to screwing up the license entirely). I wasn't originally planning on keeping the code for more than a few days as a proof of concept before rewriting it from scratch, but circumstances took that away.

Running (live) code has been corrected as above.
